import type { GraphEdge, GraphNode, GraphSnapshot } from './types.js';

const ts = {
  createdAt: '2026-01-15T10:00:00.000Z',
  updatedAt: '2026-03-20T12:00:00.000Z',
};

export const DEMO_NODES: GraphNode[] = [
  {
    id: 'n_acme',
    label: 'Acme Corp',
    type: 'company',
    description: 'Enterprise customer on Invoice AI + Sales AI',
    properties: { industry: 'Manufacturing', region: 'EMEA', arr: 240000 },
    knowledgeSourceIds: ['ks_crm'],
    tags: ['customer', 'enterprise'],
    ...ts,
  },
  {
    id: 'n_northwind',
    label: 'Northwind Traders',
    type: 'company',
    description: 'Mid-market supply-chain prospect',
    properties: { industry: 'Wholesale', region: 'NA', arr: 48000 },
    knowledgeSourceIds: ['ks_crm'],
    tags: ['prospect'],
    ...ts,
  },
  {
    id: 'n_maya',
    label: 'Maya Chen',
    type: 'person',
    description: 'VP Finance at Acme — primary Invoice AI stakeholder',
    properties: { email: 'maya.chen@acme.example', role: 'VP Finance' },
    tags: ['champion'],
    ...ts,
  },
  {
    id: 'n_alex',
    label: 'Alex Rivera',
    type: 'person',
    description: 'Procurement lead at Northwind',
    properties: { email: 'alex@northwind.example', role: 'Procurement' },
    tags: ['buyer'],
    ...ts,
  },
  {
    id: 'n_inv_8841',
    label: 'INV-8841',
    type: 'invoice',
    description: 'Open AR invoice for Acme Q1 services',
    properties: { amount: 18500, currency: 'EUR', status: 'open' },
    knowledgeSourceIds: ['ks_erp'],
    tags: ['ar', 'finance'],
    ...ts,
  },
  {
    id: 'n_inv_9012',
    label: 'INV-9012',
    type: 'invoice',
    description: 'Paid invoice for AI Pass Professional seats',
    properties: { amount: 12000, currency: 'USD', status: 'paid' },
    knowledgeSourceIds: ['ks_erp'],
    tags: ['ar'],
    ...ts,
  },
  {
    id: 'n_invoice_ai',
    label: 'Invoice AI',
    type: 'product',
    description: 'Finance automation vertical on AI Pass',
    properties: { sku: 'vert-invoice-ai', tier: 'professional' },
    tags: ['vertical', 'finance'],
    ...ts,
  },
  {
    id: 'n_sales_ai',
    label: 'Sales AI',
    type: 'product',
    description: 'Revenue operating system vertical',
    properties: { sku: 'vert-sales-ai', tier: 'professional' },
    tags: ['vertical', 'revenue'],
    ...ts,
  },
  {
    id: 'n_policy_ar',
    label: 'AR Collection Policy',
    type: 'policy',
    description: 'Days-sales-outstanding and escalation rules',
    knowledgeSourceIds: ['ks_policies'],
    tags: ['governance', 'finance'],
    ...ts,
  },
  {
    id: 'n_doc_sow',
    label: 'Acme SOW 2026',
    type: 'document',
    description: 'Statement of work covering Invoice AI rollout',
    knowledgeSourceIds: ['ks_docs'],
    tags: ['contract'],
    ...ts,
  },
];

export const DEMO_EDGES: GraphEdge[] = [
  {
    id: 'e_acme_maya',
    sourceId: 'n_acme',
    targetId: 'n_maya',
    predicate: 'employs',
    label: 'employs',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_northwind_alex',
    sourceId: 'n_northwind',
    targetId: 'n_alex',
    predicate: 'employs',
    label: 'employs',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_acme_inv8841',
    sourceId: 'n_acme',
    targetId: 'n_inv_8841',
    predicate: 'issued',
    label: 'issued',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_acme_inv9012',
    sourceId: 'n_acme',
    targetId: 'n_inv_9012',
    predicate: 'issued',
    label: 'issued',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_inv8841_product',
    sourceId: 'n_inv_8841',
    targetId: 'n_invoice_ai',
    predicate: 'covers',
    label: 'covers',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_inv9012_product',
    sourceId: 'n_inv_9012',
    targetId: 'n_sales_ai',
    predicate: 'covers',
    label: 'covers',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_maya_champions',
    sourceId: 'n_maya',
    targetId: 'n_invoice_ai',
    predicate: 'champions',
    label: 'champions',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_alex_evaluates',
    sourceId: 'n_alex',
    targetId: 'n_sales_ai',
    predicate: 'evaluates',
    label: 'evaluates',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_inv8841_policy',
    sourceId: 'n_inv_8841',
    targetId: 'n_policy_ar',
    predicate: 'governed_by',
    label: 'governed by',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_doc_acme',
    sourceId: 'n_doc_sow',
    targetId: 'n_acme',
    predicate: 'about',
    label: 'about',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_doc_invoice_ai',
    sourceId: 'n_doc_sow',
    targetId: 'n_invoice_ai',
    predicate: 'references',
    label: 'references',
    createdAt: ts.createdAt,
  },
  {
    id: 'e_acme_uses_invoice',
    sourceId: 'n_acme',
    targetId: 'n_invoice_ai',
    predicate: 'uses',
    label: 'uses',
    createdAt: ts.createdAt,
  },
];

export function createDemoSnapshot(): GraphSnapshot {
  return {
    version: 1,
    nodes: DEMO_NODES.map((n) => ({ ...n, properties: n.properties ? { ...n.properties } : undefined })),
    edges: DEMO_EDGES.map((e) => ({ ...e })),
    updatedAt: new Date().toISOString(),
  };
}
