import type {
  Approval,
  AuditLog,
  BookkeepingEntry,
  ComplianceCheck,
  FraudAlert,
  Invoice,
  InvoiceAutomationPack,
  InvoiceWorkflow,
  TaxDeclarationLine,
  ValidationResult,
  Vendor,
  DeliveryNote,
  PurchaseOrder,
  PoInvoiceMatch,
  AccountAssignmentSuggestion,
  CashDiscountAlert,
  MaterialConsumption,
  UpcomingDelivery,
  SupplyOffer,
  SupplyChainWorkflow,
  Tender,
  UserRule,
} from '@ai-pass/shared/invoice-ai';

const TENANT = 'tenant_acme';

export const DEMO_VENDORS: Vendor[] = [
  {
    id: 'vnd_001',
    tenantId: TENANT,
    name: 'Acme Supplies GmbH',
    taxId: 'DE123456789',
    email: 'billing@acme-supplies.de',
    country: 'DE',
    riskScore: 12,
    status: 'active',
    totalSpend: 48200,
    invoiceCount: 34,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'vnd_002',
    tenantId: TENANT,
    name: 'CloudHost Pro',
    taxId: 'US987654321',
    email: 'invoices@cloudhost.pro',
    country: 'US',
    riskScore: 8,
    status: 'active',
    totalSpend: 128400,
    invoiceCount: 12,
    createdAt: '2024-11-02T08:00:00Z',
  },
  {
    id: 'vnd_003',
    tenantId: TENANT,
    name: 'MediCare Billing AG',
    taxId: 'CH556677889',
    email: 'claims@medicare-billing.ch',
    country: 'CH',
    riskScore: 45,
    status: 'review',
    totalSpend: 22100,
    invoiceCount: 8,
    createdAt: '2025-03-10T14:00:00Z',
  },
  {
    id: 'vnd_004',
    tenantId: TENANT,
    name: 'Rapid Logistics Ltd',
    taxId: 'GB112233445',
    email: 'ap@rapidlogistics.co.uk',
    country: 'GB',
    riskScore: 72,
    status: 'blocked',
    totalSpend: 8900,
    invoiceCount: 3,
    createdAt: '2025-05-01T09:00:00Z',
  },
  {
    id: 'vnd_concrete',
    tenantId: TENANT,
    name: 'Beton AG Munich',
    taxId: 'DE998877665',
    email: 'dispatch@beton-ag.de',
    country: 'DE',
    riskScore: 6,
    status: 'active',
    totalSpend: 284000,
    invoiceCount: 156,
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'vnd_gravel',
    tenantId: TENANT,
    name: 'Bremer Transporte',
    taxId: 'DE554433221',
    email: 'logistics@bremer-transporte.de',
    country: 'DE',
    riskScore: 10,
    status: 'active',
    totalSpend: 67200,
    invoiceCount: 89,
    createdAt: '2024-06-15T00:00:00Z',
  },
  {
    id: 'vnd_heidelberg',
    tenantId: TENANT,
    name: 'Heidelberg Materials Süd',
    taxId: 'DE112233445',
    email: 'quotes@heidelberg-sued.de',
    country: 'DE',
    riskScore: 8,
    status: 'active',
    totalSpend: 412000,
    invoiceCount: 210,
    createdAt: '2023-01-10T00:00:00Z',
  },
  {
    id: 'vnd_office_nordic',
    tenantId: TENANT,
    name: 'Nordic Office GmbH',
    taxId: 'DE667788990',
    email: 'sales@nordic-office.de',
    country: 'DE',
    riskScore: 18,
    status: 'active',
    totalSpend: 54000,
    invoiceCount: 22,
    createdAt: '2024-09-01T00:00:00Z',
  },
  {
    id: 'vnd_office_premium',
    tenantId: TENANT,
    name: 'Premium Interiors AG',
    taxId: 'DE445566778',
    email: 'projects@premium-interiors.ch',
    country: 'CH',
    riskScore: 22,
    status: 'active',
    totalSpend: 198000,
    invoiceCount: 41,
    createdAt: '2024-02-20T00:00:00Z',
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv_001',
    tenantId: TENANT,
    invoiceNumber: 'INV-2026-0142',
    vendorId: 'vnd_001',
    vendorName: 'Acme Supplies GmbH',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'pending_approval',
    amount: 4250.0,
    currency: 'EUR',
    taxAmount: 807.5,
    dueDate: '2026-07-15',
    items: [
      { id: 'li_1', description: 'Office supplies Q2', quantity: 1, unitPrice: 3442.5, total: 3442.5 },
      { id: 'li_2', description: 'Shipping', quantity: 1, unitPrice: 0, total: 0 },
    ],
    extractedFields: {
      invoice_number: { value: 'INV-2026-0142', confidence: 0.97 },
      vendor: { value: 'Acme Supplies GmbH', confidence: 0.95 },
      total: { value: 4250, confidence: 0.93 },
    },
    decision: 'NEEDS_INFO',
    department: 'Operations',
    uploadedAt: '2026-06-28T09:15:00Z',
    processedAt: '2026-06-28T09:16:30Z',
    projectId: 'prj_tunnel',
    purchaseOrderId: 'po_001',
    deliveryNoteId: 'dn_001',
    cashDiscountDeadline: '2026-07-12',
  },
  {
    id: 'inv_002',
    tenantId: TENANT,
    invoiceNumber: 'CH-88421',
    vendorId: 'vnd_002',
    vendorName: 'CloudHost Pro',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'approved',
    amount: 12800.0,
    currency: 'USD',
    taxAmount: 0,
    dueDate: '2026-07-01',
    items: [
      { id: 'li_3', description: 'Enterprise hosting — June', quantity: 1, unitPrice: 12800, total: 12800 },
    ],
    extractedFields: {
      invoice_number: { value: 'CH-88421', confidence: 0.99 },
      vendor: { value: 'CloudHost Pro', confidence: 0.98 },
      total: { value: 12800, confidence: 0.99 },
    },
    decision: 'PASS',
    department: 'IT',
    uploadedAt: '2026-06-27T14:30:00Z',
    processedAt: '2026-06-27T14:31:00Z',
  },
  {
    id: 'inv_003',
    tenantId: TENANT,
    invoiceNumber: 'MC-2026-0891',
    vendorId: 'vnd_003',
    vendorName: 'MediCare Billing AG',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'flagged',
    amount: 18750.0,
    currency: 'CHF',
    taxAmount: 1436.25,
    dueDate: '2026-07-20',
    items: [
      { id: 'li_4', description: 'Medical claims batch #891', quantity: 1, unitPrice: 17313.75, total: 17313.75 },
    ],
    extractedFields: {
      invoice_number: { value: 'MC-2026-0891', confidence: 0.91 },
      vendor: { value: 'MediCare Billing AG', confidence: 0.88 },
      total: { value: 18750, confidence: 0.85 },
      deepfake_score: { value: 0.72, confidence: 0.9 },
      deepfake_signals: {
        value: [
          'Low OCR confidence on vendor field',
          'Metadata timestamp mismatch with document date',
        ],
        confidence: 0.9,
      },
    },
    decision: 'NEEDS_INFO',
    department: 'Healthcare',
    uploadedAt: '2026-06-29T08:00:00Z',
    processedAt: '2026-06-29T08:02:15Z',
  },
  {
    id: 'inv_004',
    tenantId: TENANT,
    invoiceNumber: 'RL-99001',
    vendorId: 'vnd_004',
    vendorName: 'Rapid Logistics Ltd',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'rejected',
    amount: 3200.0,
    currency: 'GBP',
    items: [
      { id: 'li_5', description: 'Freight services', quantity: 1, unitPrice: 3200, total: 3200 },
    ],
    extractedFields: {
      invoice_number: { value: 'RL-99001', confidence: 0.94 },
      vendor: { value: 'Rapid Logistics Ltd', confidence: 0.96 },
      total: { value: 3200, confidence: 0.92 },
    },
    decision: 'FAIL',
    department: 'Logistics',
    uploadedAt: '2026-06-25T11:00:00Z',
    processedAt: '2026-06-25T11:01:00Z',
  },
  {
    id: 'inv_005',
    tenantId: TENANT,
    invoiceNumber: 'INV-2026-0143',
    vendorId: 'vnd_001',
    vendorName: 'Acme Supplies GmbH',
    documentType: 'invoice',
    direction: 'incoming',
    status: 'validated',
    amount: 890.5,
    currency: 'EUR',
    taxAmount: 169.2,
    dueDate: '2026-07-10',
    items: [
      { id: 'li_6', description: 'Printer cartridges', quantity: 10, unitPrice: 72.13, total: 721.3 },
    ],
    extractedFields: {
      invoice_number: { value: 'INV-2026-0143', confidence: 0.98 },
      vendor: { value: 'Acme Supplies GmbH', confidence: 0.97 },
      total: { value: 890.5, confidence: 0.96 },
    },
    decision: 'PASS',
    department: 'Operations',
    uploadedAt: '2026-06-29T10:30:00Z',
    processedAt: '2026-06-29T10:31:00Z',
  },
];

export const DEMO_FRAUD_ALERTS: FraudAlert[] = [
  {
    id: 'fraud_001',
    invoiceId: 'inv_003',
    tenantId: TENANT,
    type: 'vendor_risk',
    severity: 'high',
    title: 'Elevated vendor risk score',
    description: 'MediCare Billing AG has risk score 45 — above threshold of 40.',
    status: 'open',
    score: 0.78,
    createdAt: '2026-06-29T08:02:20Z',
  },
  {
    id: 'fraud_002',
    invoiceId: 'inv_003',
    tenantId: TENANT,
    type: 'duplicate',
    severity: 'medium',
    title: 'Potential duplicate invoice',
    description: 'Similar amount and vendor detected within 30-day window.',
    status: 'investigating',
    score: 0.62,
    createdAt: '2026-06-29T08:02:25Z',
  },
  {
    id: 'fraud_003',
    invoiceId: 'inv_004',
    tenantId: TENANT,
    type: 'vendor_risk',
    severity: 'critical',
    title: 'Blocked vendor invoice',
    description: 'Rapid Logistics Ltd is on vendor blacklist.',
    status: 'resolved',
    score: 0.95,
    createdAt: '2026-06-25T11:01:05Z',
    resolvedAt: '2026-06-25T14:00:00Z',
  },
  {
    id: 'fraud_004',
    invoiceId: 'inv_003',
    tenantId: TENANT,
    type: 'deepfake',
    severity: 'high',
    title: 'Document authenticity risk',
    description: 'Low OCR confidence on vendor field — possible document tampering',
    status: 'open',
    score: 0.72,
    createdAt: '2026-06-29T08:02:30Z',
  },
  {
    id: 'fraud_005',
    invoiceId: 'inv_001',
    tenantId: TENANT,
    type: 'legal',
    severity: 'medium',
    title: 'Legal compliance issues detected',
    description: 'Budget threshold exceeded — requires additional authorization per procurement policy',
    status: 'open',
    score: 0.58,
    createdAt: '2026-06-28T09:17:05Z',
  },
];

export const DEMO_APPROVALS: Approval[] = [
  {
    id: 'appr_001',
    invoiceId: 'inv_001',
    tenantId: TENANT,
    approverId: 'user_finance_mgr',
    approverName: 'Sarah Chen',
    level: 1,
    status: 'pending',
    requestedAt: '2026-06-28T09:17:00Z',
  },
  {
    id: 'appr_002',
    invoiceId: 'inv_002',
    tenantId: TENANT,
    approverId: 'user_cfo',
    approverName: 'David Park',
    level: 1,
    status: 'approved',
    comment: 'Within IT budget allocation',
    requestedAt: '2026-06-27T14:32:00Z',
    decidedAt: '2026-06-27T16:00:00Z',
  },
];

export const DEMO_WORKFLOWS: InvoiceWorkflow[] = [
  {
    id: 'wf_default',
    tenantId: TENANT,
    name: 'Standard Invoice Processing',
    description: 'Extract → Validate → Fraud → Approve → Payment',
    mode: 'semi_automated',
    steps: [
      { id: 's1', type: 'trigger', label: 'Invoice Uploaded', next: ['s2'] },
      { id: 's2', type: 'extract', label: 'OCR Extraction', agentId: 'agent_extraction', next: ['s3'] },
      { id: 's3', type: 'validate', label: 'Compliance Validation', agentId: 'agent_validation', next: ['s4'] },
      { id: 's4', type: 'fraud', label: 'Fraud Detection', agentId: 'agent_fraud', next: ['s5'] },
      { id: 's5', type: 'approve', label: 'Approval Routing', agentId: 'agent_approval', next: ['s6'] },
      { id: 's6', type: 'payment', label: 'Schedule Payment', agentId: 'agent_payment' },
    ],
    isActive: true,
    version: 3,
    createdAt: '2025-06-01T00:00:00Z',
    updatedAt: '2026-06-15T12:00:00Z',
  },
  {
    id: 'wf_healthcare',
    tenantId: TENANT,
    name: 'Healthcare Claims Workflow',
    description: 'Insurance pack — coverage check + medical classification',
    mode: 'semi_automated',
    steps: [
      { id: 'h1', type: 'trigger', label: 'Claim Invoice Received', next: ['h2'] },
      { id: 'h2', type: 'extract', label: 'Medical Field Extraction', agentId: 'agent_extraction', next: ['h3'] },
      { id: 'h3', type: 'validate', label: 'Coverage Verification', agentId: 'agent_compliance', next: ['h4'] },
      { id: 'h4', type: 'fraud', label: 'Claims Fraud Check', agentId: 'agent_fraud', next: ['h5'] },
      { id: 'h5', type: 'approve', label: 'Claims Approval', agentId: 'agent_approval' },
    ],
    isActive: false,
    version: 1,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
];

export const DEMO_VALIDATIONS: ValidationResult[] = [
  {
    id: 'val_001',
    invoiceId: 'inv_001',
    passed: false,
    decision: 'NEEDS_INFO',
    checks: [
      { rule: 'required_fields', passed: true, message: 'All required fields present', severity: 'info' },
      { rule: 'budget_check', passed: false, message: 'Exceeds department budget by 12%', severity: 'warning' },
      { rule: 'tax_validation', passed: true, message: 'VAT rate valid for DE', severity: 'info' },
    ],
    confidence: 0.87,
    validatedAt: '2026-06-28T09:16:30Z',
  },
  {
    id: 'val_002',
    invoiceId: 'inv_002',
    passed: true,
    decision: 'PASS',
    checks: [
      { rule: 'required_fields', passed: true, message: 'All required fields present', severity: 'info' },
      { rule: 'budget_check', passed: true, message: 'Within IT budget', severity: 'info' },
      { rule: 'vendor_status', passed: true, message: 'Vendor active', severity: 'info' },
    ],
    confidence: 0.96,
    validatedAt: '2026-06-27T14:31:00Z',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_001',
    tenantId: TENANT,
    entityType: 'invoice',
    entityId: 'inv_001',
    action: 'invoice.uploaded',
    actorId: 'demo-user',
    actorName: 'Jordan Lee',
    details: { fileName: 'acme-q2-invoice.pdf' },
    creditsUsed: 15,
    timestamp: '2026-06-28T09:15:00Z',
  },
  {
    id: 'aud_002',
    tenantId: TENANT,
    entityType: 'approval',
    entityId: 'appr_002',
    action: 'invoice.approved',
    actorId: 'user_cfo',
    actorName: 'David Park',
    details: { invoiceId: 'inv_002', amount: 12800 },
    timestamp: '2026-06-27T16:00:00Z',
  },
];

export const DEMO_AUTOMATION_PACKS: InvoiceAutomationPack[] = [
  {
    id: 'pack_insurance',
    industry: 'insurance',
    name: 'Insurance Claims Invoice Pack',
    description: 'Claims validation, medical verification, coverage cross-check, fraud scoring',
    triggers: ['invoice.uploaded', 'claim.submitted'],
    skills: ['CoverageVerificationSkill', 'MedicalClassificationSkill', 'ClaimsApprovalDecisionSkill'],
    approvalMatrix: { under_1000: 'auto', over_1000: 'manager' },
    tier: 'enterprise',
    pricingModel: 'subscription',
  },
  {
    id: 'pack_healthcare',
    industry: 'healthcare',
    name: 'Healthcare & Medical Billing Pack',
    description: 'Reimbursement validation, treatment codes, duplicate detection',
    triggers: ['invoice.uploaded', 'claim.received'],
    skills: ['TreatmentCodeVerificationSkill', 'CoverageValidationSkill', 'DuplicateDetectionSkill'],
    approvalMatrix: { all: 'clinical_review' },
    tier: 'enterprise',
    pricingModel: 'subscription',
  },
  {
    id: 'pack_financial_services',
    industry: 'financial_services',
    name: 'Financial Services Pack',
    description: 'Multi-entity allocation, tax classification, AML anomaly detection',
    triggers: ['invoice.uploaded', 'erp.sync'],
    skills: ['TaxClassificationSkill', 'AMLAnomalySkill', 'CostAllocationSkill'],
    approvalMatrix: { over_5000: 'compliance' },
    tier: 'enterprise',
    pricingModel: 'per_run',
  },
  {
    id: 'pack_public_sector',
    industry: 'public_sector',
    name: 'Public Sector Procurement Pack',
    description: 'Tender compliance, documentation validation, budget authorization',
    triggers: ['invoice.received', 'tender.closed'],
    skills: ['BudgetValidationSkill', 'ComplianceCheckSkill', 'AuditExportSkill'],
    approvalMatrix: { all: 'multi_department' },
    tier: 'professional',
    pricingModel: 'subscription',
  },
  {
    id: 'pack_construction',
    industry: 'construction',
    name: 'Construction Procure-to-Pay Pack',
    description:
      'Digital delivery notes, PO matching, 3-way invoice verification, AI account assignments, cash discount tracking — inspired by comstruct.com',
    triggers: ['invoice.uploaded', 'delivery_note.signed', 'purchase_order.created'],
    skills: [
      'DeliveryNoteMatchSkill',
      'PoInvoiceMatchSkill',
      'QuantityPriceVerifySkill',
      'AccountAssignmentSkill',
      'CashDiscountSkill',
      'MaterialConsumptionSkill',
    ],
    approvalMatrix: { under_5000: 'site_manager', over_5000: 'finance' },
    tier: 'enterprise',
    pricingModel: 'subscription',
  },
  {
    id: 'pack_supply_chain',
    industry: 'construction',
    name: 'Supply Chain Sourcing Pack',
    description:
      'Multi-vendor offer intake, side-by-side comparison, user-defined procurement rules, and AI recommendations for construction materials',
    triggers: ['offer.received', 'rfq.created', 'quote.uploaded'],
    skills: [
      'OfferParseSkill',
      'OfferCompareSkill',
      'ProcurementRulesSkill',
      'VendorRiskSkill',
      'PoMatchSkill',
      'AwardRecommendationSkill',
    ],
    approvalMatrix: { under_10000: 'procurement', over_10000: 'finance' },
    tier: 'enterprise',
    pricingModel: 'subscription',
  },
];

export const DEFAULT_SUPPLY_CHAIN_RULES: UserRule[] = [
  {
    id: 'rule_reject_risk',
    name: 'Reject if vendor risk > 40',
    enabled: true,
    scope: 'global',
    condition: { field: 'vendor_risk', operator: 'gt', value: 40 },
    action: 'reject',
  },
  {
    id: 'rule_prefer_price_fast',
    name: 'Prefer lowest price if lead time < 14 days',
    enabled: true,
    scope: 'global',
    condition: { field: 'lead_time', operator: 'lt', value: 14 },
    action: 'prefer',
  },
  {
    id: 'rule_compliance',
    name: 'Warn if compliance score < 90',
    enabled: true,
    scope: 'global',
    condition: { field: 'compliance', operator: 'lt', value: 90 },
    action: 'warn',
  },
  {
    id: 'rule_po_match',
    name: 'Require revision if PO match < 80',
    enabled: true,
    scope: 'global',
    condition: { field: 'po_match', operator: 'lt', value: 80 },
    action: 'require_revision',
  },
  {
    id: 'rule_tunnel_budget',
    name: 'Tunnel budget cap (€250k)',
    enabled: true,
    scope: 'tender',
    tenderId: 'tnd_tunnel_241',
    condition: { field: 'total', operator: 'gt', value: 250000 },
    action: 'reject',
  },
];

export const DEMO_TENDERS: Tender[] = [
  {
    id: 'tnd_tunnel_241',
    tenantId: TENANT,
    title: 'Tunnel Lot 241 — Concrete supply',
    project: 'Tunnel Lot 241',
    projectId: 'prj_tunnel',
    deadline: '2026-08-15',
    status: 'open',
    requirements: [
      'C30/37 concrete, 2,400 m³ total',
      'EN 206 certification required',
      'Delivery within 21 days of award',
      'Site access Mon–Fri 06:00–18:00',
    ],
    invitedVendors: ['vnd_concrete', 'vnd_gravel', 'vnd_heidelberg', 'vnd_004'],
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'tnd_office_q3',
    tenantId: TENANT,
    title: 'Office fit-out Q3',
    project: 'HQ Renovation — Floor 3',
    projectId: 'prj_hq',
    deadline: '2026-09-30',
    status: 'open',
    requirements: [
      'Modular workstations × 48',
      'Meeting room AV package',
      'Flooring and lighting per spec v2.1',
      'Installation during weekends only',
    ],
    invitedVendors: ['vnd_001', 'vnd_003', 'vnd_office_nordic', 'vnd_office_premium'],
    createdAt: '2026-06-10T10:00:00Z',
  },
];

export const DEMO_SUPPLY_OFFERS: SupplyOffer[] = [
  {
    id: 'offer_tunnel_beton',
    tenantId: TENANT,
    tenderId: 'tnd_tunnel_241',
    rfqId: 'tnd_tunnel_241',
    rfqTitle: 'Tunnel Lot 241 — Concrete supply',
    category: 'concrete',
    vendorId: 'vnd_concrete',
    vendorName: 'Beton AG Munich',
    quoteNumber: 'BET-241-2026',
    netAmount: 198400,
    vatAmount: 37696,
    totalAmount: 236096,
    currency: 'EUR',
    leadTimeDays: 14,
    paymentTerms: 'Net 30, 2% Skonto 10d',
    vendorRiskScore: 6,
    complianceScore: 94,
    poMatchScore: 88,
    validityDate: '2026-08-01',
    items: [{ description: 'C30/37 ready-mix concrete', quantity: 2400, unit: 'm³', unitPrice: 82.67 }],
    status: 'compared',
    receivedAt: '2026-06-12T09:00:00Z',
    projectId: 'prj_tunnel',
    projectName: 'Tunnel Lot 241',
  },
  {
    id: 'offer_tunnel_bremer',
    tenantId: TENANT,
    tenderId: 'tnd_tunnel_241',
    rfqId: 'tnd_tunnel_241',
    rfqTitle: 'Tunnel Lot 241 — Concrete supply',
    category: 'concrete',
    vendorId: 'vnd_gravel',
    vendorName: 'Bremer Transporte',
    quoteNumber: 'BRE-241-Q2',
    netAmount: 205200,
    vatAmount: 38988,
    totalAmount: 244188,
    currency: 'EUR',
    leadTimeDays: 10,
    paymentTerms: 'Net 45',
    vendorRiskScore: 10,
    complianceScore: 89,
    poMatchScore: 82,
    validityDate: '2026-07-28',
    items: [{ description: 'C30/37 concrete incl. transport', quantity: 2400, unit: 'm³', unitPrice: 85.5 }],
    status: 'compared',
    receivedAt: '2026-06-14T11:30:00Z',
    projectId: 'prj_tunnel',
    projectName: 'Tunnel Lot 241',
  },
  {
    id: 'offer_tunnel_heidelberg',
    tenantId: TENANT,
    tenderId: 'tnd_tunnel_241',
    rfqId: 'tnd_tunnel_241',
    rfqTitle: 'Tunnel Lot 241 — Concrete supply',
    category: 'concrete',
    vendorId: 'vnd_heidelberg',
    vendorName: 'Heidelberg Materials Süd',
    quoteNumber: 'HDM-241-8842',
    netAmount: 201600,
    vatAmount: 38304,
    totalAmount: 239904,
    currency: 'EUR',
    leadTimeDays: 12,
    paymentTerms: 'Net 30',
    vendorRiskScore: 8,
    complianceScore: 96,
    poMatchScore: 91,
    validityDate: '2026-08-05',
    items: [{ description: 'C30/37-F3-GK16 concrete', quantity: 2400, unit: 'm³', unitPrice: 84 }],
    status: 'parsed',
    receivedAt: '2026-06-15T08:00:00Z',
    projectId: 'prj_tunnel',
    projectName: 'Tunnel Lot 241',
  },
  {
    id: 'offer_tunnel_rapid',
    tenantId: TENANT,
    tenderId: 'tnd_tunnel_241',
    rfqId: 'tnd_tunnel_241',
    rfqTitle: 'Tunnel Lot 241 — Concrete supply',
    category: 'logistics',
    vendorId: 'vnd_004',
    vendorName: 'Rapid Logistics Ltd',
    quoteNumber: 'RL-241-99001',
    netAmount: 192000,
    vatAmount: 36480,
    totalAmount: 228480,
    currency: 'EUR',
    leadTimeDays: 7,
    paymentTerms: 'Prepayment 50%',
    vendorRiskScore: 72,
    complianceScore: 78,
    poMatchScore: 62,
    validityDate: '2026-07-20',
    items: [{ description: 'C30/37 concrete (imported)', quantity: 2400, unit: 'm³', unitPrice: 80 }],
    status: 'received',
    receivedAt: '2026-06-16T14:00:00Z',
    projectId: 'prj_tunnel',
    projectName: 'Tunnel Lot 241',
  },
  {
    id: 'offer_office_acme',
    tenantId: TENANT,
    tenderId: 'tnd_office_q3',
    rfqId: 'tnd_office_q3',
    rfqTitle: 'Office fit-out Q3',
    category: 'office_supplies',
    vendorId: 'vnd_001',
    vendorName: 'Acme Supplies GmbH',
    quoteNumber: 'ACM-FIT-Q3',
    netAmount: 142800,
    vatAmount: 27132,
    totalAmount: 169932,
    currency: 'EUR',
    leadTimeDays: 28,
    paymentTerms: 'Net 30',
    vendorRiskScore: 12,
    complianceScore: 91,
    poMatchScore: 90,
    validityDate: '2026-09-15',
    items: [
      { description: 'Modular workstations × 48', quantity: 48, unit: 'pcs', unitPrice: 1850 },
      { description: 'Meeting room AV', quantity: 1, unit: 'lot', unitPrice: 18400 },
    ],
    status: 'compared',
    receivedAt: '2026-06-18T09:00:00Z',
    projectId: 'prj_hq',
    projectName: 'HQ Renovation — Floor 3',
  },
  {
    id: 'offer_office_nordic',
    tenantId: TENANT,
    tenderId: 'tnd_office_q3',
    rfqId: 'tnd_office_q3',
    rfqTitle: 'Office fit-out Q3',
    category: 'office_supplies',
    vendorId: 'vnd_office_nordic',
    vendorName: 'Nordic Office GmbH',
    quoteNumber: 'NOR-F3-2026',
    netAmount: 138600,
    vatAmount: 26334,
    totalAmount: 164934,
    currency: 'EUR',
    leadTimeDays: 35,
    paymentTerms: 'Net 45, 3% early pay',
    vendorRiskScore: 18,
    complianceScore: 88,
    poMatchScore: 85,
    validityDate: '2026-09-20',
    items: [{ description: 'Workstations + flooring package', quantity: 1, unit: 'lot', unitPrice: 138600 }],
    status: 'compared',
    receivedAt: '2026-06-19T10:00:00Z',
    projectId: 'prj_hq',
    projectName: 'HQ Renovation — Floor 3',
  },
  {
    id: 'offer_office_medi',
    tenantId: TENANT,
    tenderId: 'tnd_office_q3',
    rfqId: 'tnd_office_q3',
    rfqTitle: 'Office fit-out Q3',
    category: 'office_supplies',
    vendorId: 'vnd_003',
    vendorName: 'MediCare Billing AG',
    quoteNumber: 'MED-OFF-Q3',
    netAmount: 156800,
    vatAmount: 29792,
    totalAmount: 186592,
    currency: 'EUR',
    leadTimeDays: 21,
    paymentTerms: 'Net 30',
    vendorRiskScore: 45,
    complianceScore: 82,
    poMatchScore: 78,
    validityDate: '2026-09-01',
    items: [{ description: 'Premium fit-out incl. lighting', quantity: 1, unit: 'lot', unitPrice: 156800 }],
    status: 'received',
    receivedAt: '2026-06-20T08:30:00Z',
    projectId: 'prj_hq',
    projectName: 'HQ Renovation — Floor 3',
  },
  {
    id: 'offer_office_premium',
    tenantId: TENANT,
    tenderId: 'tnd_office_q3',
    rfqId: 'tnd_office_q3',
    rfqTitle: 'Office fit-out Q3',
    category: 'office_supplies',
    vendorId: 'vnd_office_premium',
    vendorName: 'Premium Interiors AG',
    quoteNumber: 'PRM-HQ-F3',
    netAmount: 134400,
    vatAmount: 25536,
    totalAmount: 159936,
    currency: 'EUR',
    leadTimeDays: 42,
    paymentTerms: 'Net 60',
    vendorRiskScore: 22,
    complianceScore: 95,
    poMatchScore: 92,
    validityDate: '2026-10-01',
    items: [{ description: 'Full floor fit-out per spec v2.1', quantity: 1, unit: 'lot', unitPrice: 134400 }],
    status: 'received',
    receivedAt: '2026-06-21T15:00:00Z',
    projectId: 'prj_hq',
    projectName: 'HQ Renovation — Floor 3',
  },
];

export const DEMO_SUPPLY_CHAIN_WORKFLOWS: SupplyChainWorkflow[] = [
  {
    id: 'scwf_tunnel',
    tenantId: TENANT,
    rfqId: 'tnd_tunnel_241',
    title: 'Tunnel Lot 241 — Concrete supply',
    status: 'evaluating',
    currentStep: 'evaluate_rules',
    steps: [
      { id: 'tender_published', label: 'Tender published', status: 'completed' },
      { id: 'collect_offers', label: 'Collect vendor quotes', status: 'completed' },
      { id: 'parse_normalize', label: 'Parse & normalize offers', status: 'completed' },
      { id: 'compare_offers', label: 'Side-by-side comparison', status: 'completed' },
      { id: 'evaluate_rules', label: 'Apply procurement rules', status: 'active' },
      { id: 'recommend_award', label: 'AI recommendation & award', status: 'pending' },
      { id: 'create_po', label: 'Create PO & notify vendor', status: 'pending' },
    ],
  },
  {
    id: 'scwf_office',
    tenantId: TENANT,
    rfqId: 'tnd_office_q3',
    title: 'Office fit-out Q3',
    status: 'comparing',
    currentStep: 'compare_offers',
    steps: [
      { id: 'tender_published', label: 'Tender published', status: 'completed' },
      { id: 'collect_offers', label: 'Collect vendor quotes', status: 'completed' },
      { id: 'parse_normalize', label: 'Parse & normalize offers', status: 'completed' },
      { id: 'compare_offers', label: 'Side-by-side comparison', status: 'active' },
      { id: 'evaluate_rules', label: 'Apply procurement rules', status: 'pending' },
      { id: 'recommend_award', label: 'AI recommendation & award', status: 'pending' },
      { id: 'create_po', label: 'Create PO & notify vendor', status: 'pending' },
    ],
  },
];

export const DEMO_TENANT_ID = TENANT;

export const DEMO_COMPLIANCE_CHECKS: ComplianceCheck[] = [
  {
    id: 'cmp_demo_001',
    invoiceId: 'inv_001',
    category: 'tax',
    rule: 'eu_vat_rate',
    passed: true,
    message: 'VAT rate valid for DE (19%)',
    severity: 'info',
    framework: 'EU_VAT',
  },
  {
    id: 'cmp_demo_002',
    invoiceId: 'inv_001',
    category: 'legal',
    rule: 'budget_authorization',
    passed: false,
    message: 'Exceeds department budget — additional authorization required',
    severity: 'warning',
    framework: 'Legal_Compliance',
  },
  {
    id: 'cmp_demo_003',
    invoiceId: 'inv_003',
    category: 'insurance',
    rule: 'coverage_eligibility',
    passed: true,
    message: 'Amount within standard coverage threshold',
    severity: 'info',
    framework: 'Insurance_Claims',
  },
];

export const DEMO_BOOKKEEPING: BookkeepingEntry[] = [
  {
    id: 'bk_demo_001',
    invoiceId: 'inv_002',
    account: '4930',
    debit: 10756.3,
    credit: 0,
    description: 'CloudHost Pro — CH-88421',
    taxCode: 'VSt19',
    postedAt: '2026-06-27T16:00:00Z',
  },
  {
    id: 'bk_demo_002',
    invoiceId: 'inv_002',
    account: '1600',
    debit: 0,
    credit: 12800,
    description: 'Accounts payable — CloudHost Pro',
    postedAt: '2026-06-27T16:00:00Z',
  },
];

export const DEMO_TAX_LINES: TaxDeclarationLine[] = [
  {
    id: 'tax_demo_001',
    invoiceId: 'inv_001',
    vatRate: 0.19,
    netAmount: 3572.27,
    vatAmount: 678.73,
    jurisdiction: 'DE',
    declarationPeriod: '2026-Q2',
  },
  {
    id: 'tax_demo_002',
    invoiceId: 'inv_003',
    vatRate: 0.077,
    netAmount: 17313.75,
    vatAmount: 1334.16,
    jurisdiction: 'CH',
    declarationPeriod: '2026-Q2',
  },
];

export const DEMO_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_001',
    tenantId: TENANT,
    poNumber: 'PO-2026-0892',
    projectId: 'prj_tunnel',
    projectName: 'Tunnel Lot 241',
    vendorId: 'vnd_001',
    vendorName: 'Acme Supplies GmbH',
    contractRef: 'CTR-2026-ACME-12',
    status: 'delivered',
    items: [
      {
        id: 'poi_1',
        description: 'Office supplies Q2',
        quantity: 1,
        unit: 'lot',
        unitPrice: 3442.5,
        total: 3442.5,
        materialCategory: 'supplies',
      },
    ],
    totalAmount: 4250,
    currency: 'EUR',
    orderedAt: '2026-06-20T08:00:00Z',
    expectedDeliveryAt: '2026-06-28T07:00:00Z',
  },
  {
    id: 'po_002',
    tenantId: TENANT,
    poNumber: 'PO-2026-1104',
    projectId: 'prj_munich',
    projectName: 'Munich Tower',
    vendorId: 'vnd_concrete',
    vendorName: 'Beton AG Munich',
    contractRef: 'CTR-BETON-2026',
    status: 'partial',
    items: [
      {
        id: 'poi_2',
        description: 'C30/37-F3 concrete',
        quantity: 61.5,
        unit: 'm³',
        unitPrice: 142,
        total: 8733,
        materialCategory: 'concrete',
      },
      {
        id: 'poi_3',
        description: 'RC0/23 gravel',
        quantity: 34,
        unit: 't',
        unitPrice: 48,
        total: 1632,
        materialCategory: 'bulk',
      },
    ],
    totalAmount: 10365,
    currency: 'EUR',
    orderedAt: '2026-07-04T06:00:00Z',
    expectedDeliveryAt: '2026-07-05T07:00:00Z',
  },
];

export const DEMO_DELIVERY_NOTES: DeliveryNote[] = [
  {
    id: 'dn_001',
    tenantId: TENANT,
    deliveryNumber: 'LS-2026-4521',
    projectId: 'prj_tunnel',
    projectName: 'Tunnel Lot 241',
    vendorId: 'vnd_001',
    vendorName: 'Acme Supplies GmbH',
    purchaseOrderId: 'po_001',
    flowType: 'supplier_to_site',
    status: 'matched',
    items: [
      { id: 'dni_1', description: 'Office supplies Q2', quantity: 1, unit: 'lot', materialCategory: 'supplies' },
    ],
    driverName: 'K. Weber',
    receiverName: 'Site Manager',
    signedAt: '2026-06-28T07:45:00Z',
    photoProof: true,
    pdfGenerated: true,
    deliveredAt: '2026-06-28T07:30:00Z',
    createdAt: '2026-06-28T07:20:00Z',
  },
  {
    id: 'dn_002',
    tenantId: TENANT,
    deliveryNumber: 'LS-2026-4522',
    projectId: 'prj_munich',
    projectName: 'Munich Tower',
    vendorId: 'vnd_concrete',
    vendorName: 'Beton AG Munich',
    purchaseOrderId: 'po_002',
    flowType: 'plant_to_site',
    status: 'signed',
    items: [
      { id: 'dni_2', description: 'C30/37-F3 concrete', quantity: 7.5, unit: 'm³', materialCategory: 'concrete' },
    ],
    driverName: 'M. Fischer',
    receiverName: 'Foreman',
    signedAt: '2026-07-05T08:30:00Z',
    photoProof: true,
    pdfGenerated: true,
    deliveredAt: '2026-07-05T08:15:00Z',
    createdAt: '2026-07-05T07:00:00Z',
  },
  {
    id: 'dn_003',
    tenantId: TENANT,
    deliveryNumber: 'LS-2026-4523',
    projectId: 'prj_munich',
    projectName: 'Munich Tower',
    vendorId: 'vnd_gravel',
    vendorName: 'Bremer Transporte',
    purchaseOrderId: 'po_002',
    flowType: 'supplier_to_site',
    status: 'delivered',
    items: [
      { id: 'dni_3', description: 'RC0/23 gravel', quantity: 34, unit: 't', materialCategory: 'bulk' },
    ],
    driverName: 'T. Bremer',
    receiverName: 'Site Lead',
    signedAt: '2026-07-05T13:10:00Z',
    photoProof: true,
    pdfGenerated: true,
    deliveredAt: '2026-07-05T13:00:00Z',
    createdAt: '2026-07-05T10:00:00Z',
  },
];

export const DEMO_PO_MATCHES: PoInvoiceMatch[] = [
  {
    id: 'match_001',
    invoiceId: 'inv_001',
    purchaseOrderId: 'po_001',
    deliveryNoteId: 'dn_001',
    matched: true,
    quantityMatch: true,
    priceMatch: true,
    contractMatch: true,
    varianceAmount: 0,
    variancePercent: 0,
    message: '3-way match OK — PO PO-2026-0892, delivery LS-2026-4521',
    checkedAt: '2026-06-28T09:16:30Z',
  },
];

export const DEMO_ACCOUNT_SUGGESTIONS: AccountAssignmentSuggestion[] = [
  {
    id: 'acct_001',
    invoiceId: 'inv_001',
    account: '4980',
    costCenter: 'prj_tunnel',
    projectId: 'prj_tunnel',
    confidence: 0.96,
    reason: 'AI suggestion from matched PO contract CTR-2026-ACME-12',
  },
  {
    id: 'acct_002',
    invoiceId: 'inv_002',
    account: '4930',
    costCenter: 'CC-IT',
    confidence: 0.92,
    reason: 'AI suggestion from material category and vendor history',
  },
];

export const DEMO_CASH_DISCOUNTS: CashDiscountAlert[] = [
  {
    id: 'skonto_001',
    invoiceId: 'inv_001',
    discountPercent: 2,
    discountAmount: 85,
    deadline: '2026-07-12',
    daysRemaining: 7,
    status: 'available',
  },
  {
    id: 'skonto_002',
    invoiceId: 'inv_005',
    discountPercent: 2,
    discountAmount: 17.81,
    deadline: '2026-07-13',
    daysRemaining: 2,
    status: 'expiring_soon',
  },
];

export const DEMO_UPCOMING_DELIVERIES: UpcomingDelivery[] = [
  {
    id: 'del_001',
    tenantId: TENANT,
    projectName: 'Munich Tower',
    vendorName: 'Beton AG Munich',
    description: 'C30/37-F3-GK16 concrete',
    quantity: 8,
    unit: 'm³',
    scheduledAt: '2026-07-05T10:00:00Z',
    status: 'ordered',
  },
  {
    id: 'del_002',
    tenantId: TENANT,
    projectName: 'Munich Tower',
    vendorName: 'Bremer Transporte',
    description: 'RC0/23 gravel',
    quantity: 34,
    unit: 't',
    scheduledAt: '2026-07-05T13:00:00Z',
    status: 'in_transit',
  },
  {
    id: 'del_003',
    tenantId: TENANT,
    projectName: 'Tunnel Lot 241',
    vendorName: 'Bontong Bammtental AG',
    description: 'Sample concrete A100',
    quantity: 12,
    unit: 'm³',
    scheduledAt: '2026-07-05T08:30:00Z',
    status: 'confirmed',
  },
];

export const DEMO_MATERIAL_CONSUMPTION: MaterialConsumption[] = [
  { id: 'mc_1', tenantId: TENANT, projectId: 'prj_munich', projectName: 'Munich Tower', category: 'Concrete', quantity: 453, unit: 'm³', co2Tonnes: 412, period: '2026-Q2' },
  { id: 'mc_2', tenantId: TENANT, projectId: 'prj_munich', projectName: 'Munich Tower', category: 'Rebar', quantity: 10745, unit: 'kg', co2Tonnes: 318, period: '2026-Q2' },
  { id: 'mc_3', tenantId: TENANT, projectId: 'prj_tunnel', projectName: 'Tunnel Lot 241', category: 'Bulk material', quantity: 2800, unit: 'm³', co2Tonnes: 412, period: '2026-Q2' },
  { id: 'mc_4', tenantId: TENANT, projectId: 'prj_munich', projectName: 'Munich Tower', category: 'Disposal', quantity: 2500, unit: 'kg', co2Tonnes: 98, period: '2026-Q2' },
];

export function getDashboardStats(invoices: Invoice[], fraudAlerts: FraudAlert[], vendors: Vendor[]) {
  const today = new Date().toISOString().slice(0, 10);
  const todayProcessed = invoices.filter((i) => i.processedAt?.startsWith(today)).length;
  const awaitingApproval = invoices.filter((i) => i.status === 'pending_approval').length;
  const openFraud = fraudAlerts.filter((a) => a.status === 'open' || a.status === 'investigating').length;
  const fakeInvoicesDetected = fraudAlerts.filter((a) => a.type === 'deepfake').length;
  const monthlySpend = invoices
    .filter((i) => i.status === 'approved' || i.status === 'paid')
    .reduce((sum, i) => sum + i.amount, 0);
  const approved = invoices.filter((i) => i.status === 'approved' || i.status === 'paid').length;
  const total = invoices.length;

  return {
    todayProcessed,
    awaitingApproval,
    fraudAlerts: openFraud,
    fakeInvoicesDetected,
    monthlySpend,
    vendorCount: vendors.length,
    approvalRate: total > 0 ? Math.round((approved / total) * 100) : 0,
  };
}
