import type { Tool } from './types.js';
import type { ToolProfileExtras } from './types.js';

function profile(partial: Partial<ToolProfileExtras> & Pick<ToolProfileExtras, 'taxonomy' | 'general'>): ToolProfileExtras {
  return {
    capabilities: partial.capabilities ?? ['text'],
    supportedModels: partial.supportedModels ?? ['other'],
    deployment: partial.deployment ?? ['cloud', 'api'],
    pricing: partial.pricing ?? ['freemium'],
    integrations: partial.integrations ?? [],
    compliance: partial.compliance ?? [],
    taxonomy: partial.taxonomy,
    subcategories: partial.subcategories ?? [],
    contextWindow: partial.contextWindow,
    languages: partial.languages ?? ['en'],
    apiAvailable: partial.apiAvailable ?? true,
    localDeployable: partial.localDeployable ?? false,
    openSource: partial.openSource ?? false,
    latencyMs: partial.latencyMs,
    installMethods: partial.installMethods ?? ['api_key', 'oauth'],
    general: partial.general,
  };
}

/**
 * External AI product catalog entries — expands Discovery beyond marketplace apps
 * toward a large searchable enterprise AI directory that can still Install/Connect/Orchestrate.
 */
export const EXTERNAL_CATALOG: Tool[] = [
  {
    id: 'ext_claude',
    slug: 'anthropic-claude',
    name: 'Anthropic Claude',
    description: 'Enterprise-grade LLM for reasoning, coding, and long-context analysis with strong safety defaults.',
    category: 'ai_agents',
    tags: ['llm', 'reasoning', 'coding', 'enterprise'],
    developerId: 'dev_anthropic',
    developerName: 'Anthropic',
    pricingModel: 'subscription',
    priceMonthly: 20,
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    installCount: 48200,
    rating: 4.8,
    reviewCount: 2100,
    trustScore: 94,
    trustBadges: ['Gold Certified', 'Enterprise Ready'],
    creditsRequired: 2,
    estimatedCostPerRun: 0.04,
    supportedPlatforms: ['web', 'api'],
    modelsUsed: ['claude-sonnet', 'claude-opus'],
    screenshots: [],
    features: ['Long context', 'Tool use', 'Artifacts', 'Constitutional AI'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/anthropic-claude',
    workspaceRoute: '/workspace/playground?provider=anthropic',
    presenceAuditRoute: '/workspace/presence',
    source: 'external',
    profile: profile({
      taxonomy: ['text_llm', 'coding', 'enterprise_ai'],
      subcategories: ['Chatbots', 'Code Generation', 'Prompt Engineering'],
      capabilities: ['text', 'code', 'vision', 'multimodal'],
      supportedModels: ['claude'],
      deployment: ['cloud', 'api'],
      pricing: ['subscription', 'pay_as_you_go', 'enterprise'],
      integrations: ['slack', 'notion', 'github'],
      compliance: ['gdpr', 'soc2', 'iso27001'],
      contextWindow: 200000,
      languages: ['en', 'de', 'fr', 'es', 'ja'],
      latencyMs: 720,
      installMethods: ['api_key', 'oauth', 'marketplace'],
      general: {
        website: 'https://www.anthropic.com',
        developer: 'Anthropic',
        country: 'US',
        launchDate: '2023-03-01',
        logoUrl: '/discover/logos/claude.svg',
      },
    }),
  },
  {
    id: 'ext_gpt',
    slug: 'openai-gpt',
    name: 'OpenAI GPT',
    description: 'Flagship multimodal models for chat, coding, vision, and agent tool calling.',
    category: 'ai_agents',
    tags: ['llm', 'gpt', 'multimodal', 'agents'],
    developerId: 'dev_openai',
    developerName: 'OpenAI',
    pricingModel: 'pay_per_use',
    pricePerUse: 0.02,
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    installCount: 92000,
    rating: 4.7,
    reviewCount: 5400,
    trustScore: 91,
    trustBadges: ['Gold Certified'],
    creditsRequired: 2,
    estimatedCostPerRun: 0.03,
    supportedPlatforms: ['web', 'api'],
    modelsUsed: ['gpt-4.1', 'gpt-4o'],
    screenshots: [],
    features: ['Multimodal', 'Function calling', 'Assistants API'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/openai-gpt',
    workspaceRoute: '/workspace/playground?provider=openai',
    source: 'external',
    profile: profile({
      taxonomy: ['text_llm', 'coding', 'enterprise_ai'],
      subcategories: ['Chatbots', 'Code Generation', 'API Development'],
      capabilities: ['text', 'vision', 'audio', 'code', 'multimodal'],
      supportedModels: ['gpt'],
      deployment: ['cloud', 'api'],
      pricing: ['freemium', 'pay_as_you_go', 'enterprise'],
      integrations: ['slack', 'teams', 'zapier', 'github'],
      compliance: ['gdpr', 'soc2'],
      contextWindow: 128000,
      latencyMs: 680,
      installMethods: ['api_key', 'oauth', 'marketplace'],
      general: {
        website: 'https://openai.com',
        developer: 'OpenAI',
        country: 'US',
        launchDate: '2022-11-30',
        logoUrl: '/discover/logos/openai.svg',
      },
    }),
  },
  {
    id: 'ext_deepseek',
    slug: 'deepseek',
    name: 'DeepSeek',
    description: 'High-efficiency reasoning and coding models with strong cost performance.',
    category: 'developer_tools',
    tags: ['llm', 'coding', 'reasoning', 'cost'],
    developerId: 'dev_deepseek',
    developerName: 'DeepSeek',
    pricingModel: 'pay_per_use',
    pricePerUse: 0.005,
    certified: false,
    enterpriseReady: true,
    openSource: true,
    featured: true,
    trending: true,
    installCount: 31000,
    rating: 4.6,
    reviewCount: 980,
    trustScore: 84,
    trustBadges: ['Open Source', 'Silver Certified'],
    creditsRequired: 1,
    estimatedCostPerRun: 0.01,
    supportedPlatforms: ['api', 'local'],
    modelsUsed: ['deepseek-r1', 'deepseek-v3'],
    screenshots: [],
    features: ['Reasoning', 'Coding', 'Open weights'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/deepseek',
    workspaceRoute: '/workspace/playground?provider=deepseek',
    source: 'external',
    profile: profile({
      taxonomy: ['text_llm', 'coding', 'research'],
      subcategories: ['Code Generation', 'Chatbots'],
      capabilities: ['text', 'code'],
      supportedModels: ['deepseek'],
      deployment: ['cloud', 'api', 'local', 'docker'],
      pricing: ['free', 'pay_as_you_go'],
      integrations: ['github', 'webhook'],
      compliance: [],
      contextWindow: 64000,
      openSource: true,
      localDeployable: true,
      latencyMs: 900,
      installMethods: ['api_key', 'docker', 'github'],
      general: {
        website: 'https://www.deepseek.com',
        developer: 'DeepSeek',
        country: 'CN',
        launchDate: '2024-01-01',
      },
    }),
  },
  {
    id: 'ext_llama',
    slug: 'meta-llama',
    name: 'Meta Llama',
    description: 'Open-weight foundation models for private and on-prem enterprise deployment.',
    category: 'developer_tools',
    tags: ['llm', 'open-source', 'local', 'private-ai'],
    developerId: 'dev_meta',
    developerName: 'Meta',
    pricingModel: 'free',
    certified: true,
    enterpriseReady: true,
    openSource: true,
    featured: true,
    trending: false,
    installCount: 67000,
    rating: 4.5,
    reviewCount: 3200,
    trustScore: 88,
    trustBadges: ['Open Source', 'Silver Certified'],
    creditsRequired: 0,
    supportedPlatforms: ['local', 'api', 'docker'],
    modelsUsed: ['llama-3.3', 'llama-4'],
    screenshots: [],
    features: ['Open weights', 'On-prem', 'Fine-tuning'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/meta-llama',
    workspaceRoute: '/workspace/playground?provider=meta',
    source: 'external',
    profile: profile({
      taxonomy: ['text_llm', 'enterprise_ai', 'coding'],
      subcategories: ['Chatbots', 'Code Generation'],
      capabilities: ['text', 'code', 'multimodal'],
      supportedModels: ['llama'],
      deployment: ['local', 'on_premise', 'docker', 'api'],
      pricing: ['free', 'enterprise'],
      integrations: ['github'],
      compliance: ['gdpr'],
      contextWindow: 128000,
      openSource: true,
      localDeployable: true,
      apiAvailable: true,
      latencyMs: 1100,
      installMethods: ['docker', 'github', 'sdk'],
      general: {
        website: 'https://llama.meta.com',
        developer: 'Meta',
        country: 'US',
        launchDate: '2023-07-18',
      },
    }),
  },
  {
    id: 'ext_mistral',
    slug: 'mistral-ai',
    name: 'Mistral AI',
    description: 'European open and commercial LLMs optimized for latency and sovereign deployments.',
    category: 'ai_agents',
    tags: ['llm', 'europe', 'sovereign', 'open-source'],
    developerId: 'dev_mistral',
    developerName: 'Mistral AI',
    pricingModel: 'subscription',
    priceMonthly: 15,
    certified: true,
    enterpriseReady: true,
    openSource: true,
    featured: false,
    trending: true,
    installCount: 24000,
    rating: 4.5,
    reviewCount: 760,
    trustScore: 89,
    trustBadges: ['Gold Certified', 'GDPR'],
    creditsRequired: 1,
    estimatedCostPerRun: 0.02,
    supportedPlatforms: ['api', 'local'],
    modelsUsed: ['mistral-large', 'mistral-small'],
    screenshots: [],
    features: ['EU hosting options', 'Open weights', 'Low latency'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/mistral-ai',
    workspaceRoute: '/workspace/playground?provider=mistral',
    source: 'external',
    profile: profile({
      taxonomy: ['text_llm', 'enterprise_ai', 'coding'],
      capabilities: ['text', 'code'],
      supportedModels: ['mistral'],
      deployment: ['cloud', 'api', 'local', 'on_premise'],
      pricing: ['freemium', 'subscription', 'enterprise'],
      integrations: ['github', 'webhook'],
      compliance: ['gdpr', 'iso27001'],
      contextWindow: 128000,
      openSource: true,
      localDeployable: true,
      languages: ['en', 'fr', 'de', 'es'],
      latencyMs: 650,
      installMethods: ['api_key', 'docker', 'marketplace'],
      general: {
        website: 'https://mistral.ai',
        developer: 'Mistral AI',
        country: 'FR',
        launchDate: '2023-09-27',
      },
    }),
  },
  {
    id: 'ext_gemini',
    slug: 'google-gemini',
    name: 'Google Gemini',
    description: 'Google multimodal models with strong vision, long context, and Workspace integrations.',
    category: 'ai_agents',
    tags: ['llm', 'multimodal', 'vision', 'google'],
    developerId: 'dev_google',
    developerName: 'Google',
    pricingModel: 'pay_per_use',
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    installCount: 51000,
    rating: 4.6,
    reviewCount: 1900,
    trustScore: 90,
    trustBadges: ['Gold Certified'],
    creditsRequired: 2,
    estimatedCostPerRun: 0.025,
    supportedPlatforms: ['web', 'api'],
    modelsUsed: ['gemini-2.5-pro', 'gemini-flash'],
    screenshots: [],
    features: ['Native multimodal', 'Long context', 'Workspace'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/google-gemini',
    workspaceRoute: '/workspace/playground?provider=google',
    source: 'external',
    profile: profile({
      taxonomy: ['text_llm', 'image', 'enterprise_ai'],
      capabilities: ['text', 'vision', 'audio', 'video', 'code', 'multimodal'],
      supportedModels: ['gemini'],
      deployment: ['cloud', 'api'],
      pricing: ['freemium', 'pay_as_you_go', 'enterprise'],
      integrations: ['google_drive', 'slack', 'github'],
      compliance: ['gdpr', 'soc2', 'iso27001'],
      contextWindow: 1000000,
      latencyMs: 700,
      installMethods: ['api_key', 'oauth', 'marketplace'],
      general: {
        website: 'https://deepmind.google/technologies/gemini/',
        developer: 'Google DeepMind',
        country: 'US',
        launchDate: '2023-12-06',
      },
    }),
  },
  {
    id: 'ext_qwen',
    slug: 'alibaba-qwen',
    name: 'Alibaba Qwen',
    description: 'Multilingual open and commercial models strong in coding and agent workflows.',
    category: 'developer_tools',
    tags: ['llm', 'multilingual', 'coding', 'open-source'],
    developerId: 'dev_alibaba',
    developerName: 'Alibaba',
    pricingModel: 'free',
    certified: false,
    enterpriseReady: true,
    openSource: true,
    featured: false,
    trending: true,
    installCount: 18000,
    rating: 4.4,
    reviewCount: 540,
    trustScore: 82,
    trustBadges: ['Open Source'],
    creditsRequired: 0,
    supportedPlatforms: ['api', 'local'],
    modelsUsed: ['qwen-2.5', 'qwen-max'],
    screenshots: [],
    features: ['Multilingual', 'Coding', 'Open weights'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/alibaba-qwen',
    workspaceRoute: '/workspace/playground?provider=qwen',
    source: 'external',
    profile: profile({
      taxonomy: ['text_llm', 'coding', 'research'],
      capabilities: ['text', 'code', 'vision', 'multimodal'],
      supportedModels: ['qwen'],
      deployment: ['cloud', 'api', 'local', 'docker'],
      pricing: ['free', 'pay_as_you_go'],
      integrations: ['github'],
      compliance: [],
      contextWindow: 128000,
      openSource: true,
      localDeployable: true,
      languages: ['en', 'zh', 'de', 'ja'],
      latencyMs: 850,
      installMethods: ['api_key', 'docker', 'github'],
      general: {
        website: 'https://qwenlm.github.io',
        developer: 'Alibaba Cloud',
        country: 'CN',
        launchDate: '2023-08-01',
      },
    }),
  },
  {
    id: 'ext_midjourney',
    slug: 'midjourney',
    name: 'Midjourney',
    description: 'High-quality generative image platform for creative and product design teams.',
    category: 'marketing',
    tags: ['image', 'design', 'generation'],
    developerId: 'dev_midjourney',
    developerName: 'Midjourney',
    pricingModel: 'subscription',
    priceMonthly: 30,
    certified: false,
    enterpriseReady: false,
    openSource: false,
    featured: true,
    trending: true,
    installCount: 74000,
    rating: 4.7,
    reviewCount: 4100,
    trustScore: 76,
    trustBadges: [],
    creditsRequired: 3,
    estimatedCostPerRun: 0.08,
    supportedPlatforms: ['web'],
    modelsUsed: ['midjourney-v6'],
    screenshots: [],
    features: ['Image generation', 'Style consistency', 'Upscaling'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/midjourney',
    source: 'external',
    profile: profile({
      taxonomy: ['image', 'design', 'marketing'],
      subcategories: ['Image Generation', 'Upscaling', 'UI Design'],
      capabilities: ['vision', 'multimodal'],
      supportedModels: ['other'],
      deployment: ['cloud'],
      pricing: ['subscription'],
      integrations: ['slack'],
      compliance: [],
      apiAvailable: false,
      latencyMs: 12000,
      installMethods: ['oauth'],
      general: {
        website: 'https://www.midjourney.com',
        developer: 'Midjourney',
        country: 'US',
        launchDate: '2022-07-12',
      },
    }),
  },
  {
    id: 'ext_elevenlabs',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Voice synthesis, cloning, and speech AI for products and content teams.',
    category: 'voice_ai',
    tags: ['audio', 'tts', 'voice-cloning'],
    developerId: 'dev_elevenlabs',
    developerName: 'ElevenLabs',
    pricingModel: 'subscription',
    priceMonthly: 22,
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    installCount: 29000,
    rating: 4.6,
    reviewCount: 1200,
    trustScore: 85,
    trustBadges: ['Silver Certified'],
    creditsRequired: 2,
    estimatedCostPerRun: 0.05,
    supportedPlatforms: ['web', 'api'],
    modelsUsed: ['eleven-multilingual'],
    screenshots: [],
    features: ['TTS', 'Voice cloning', 'Dubbing'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/elevenlabs',
    workspaceRoute: '/workspace/workflows?addTool=elevenlabs',
    source: 'external',
    profile: profile({
      taxonomy: ['audio', 'marketing', 'customer_support'],
      subcategories: ['Text-to-Speech', 'Voice Cloning'],
      capabilities: ['audio'],
      supportedModels: ['other'],
      deployment: ['cloud', 'api'],
      pricing: ['freemium', 'subscription', 'enterprise'],
      integrations: ['zapier', 'webhook'],
      compliance: ['gdpr', 'soc2'],
      languages: ['en', 'de', 'fr', 'es', 'ar'],
      latencyMs: 1400,
      installMethods: ['api_key', 'oauth', 'marketplace'],
      general: {
        website: 'https://elevenlabs.io',
        developer: 'ElevenLabs',
        country: 'US',
        launchDate: '2022-01-23',
      },
    }),
  },
  {
    id: 'ext_pinecone',
    slug: 'pinecone',
    name: 'Pinecone',
    description: 'Managed vector database for production RAG and semantic search workloads.',
    category: 'knowledge',
    tags: ['vector', 'rag', 'mlops'],
    developerId: 'dev_pinecone',
    developerName: 'Pinecone',
    pricingModel: 'subscription',
    priceMonthly: 50,
    certified: true,
    enterpriseReady: true,
    openSource: false,
    featured: false,
    trending: false,
    installCount: 22000,
    rating: 4.4,
    reviewCount: 680,
    trustScore: 87,
    trustBadges: ['Silver Certified', 'Enterprise Ready'],
    creditsRequired: 1,
    supportedPlatforms: ['api', 'cloud'],
    modelsUsed: [],
    screenshots: [],
    features: ['Vector search', 'Namespaces', 'Hybrid search'],
    membershipTierRequired: 'professional',
    storeRoute: '/workspace/store/apps/pinecone',
    workspaceRoute: '/workspace/knowledge',
    source: 'external',
    profile: profile({
      taxonomy: ['data_ai', 'enterprise_ai'],
      subcategories: ['Vector Databases', 'MLOps'],
      capabilities: ['text'],
      supportedModels: ['other'],
      deployment: ['cloud', 'api'],
      pricing: ['freemium', 'subscription', 'enterprise'],
      integrations: ['github', 'webhook'],
      compliance: ['gdpr', 'soc2', 'hipaa'],
      latencyMs: 40,
      installMethods: ['api_key', 'sdk', 'marketplace'],
      general: {
        website: 'https://www.pinecone.io',
        developer: 'Pinecone Systems',
        country: 'US',
        launchDate: '2019-01-01',
      },
    }),
  },
  {
    id: 'ext_runway',
    slug: 'runway',
    name: 'Runway',
    description: 'Generative video platform for editing, generation, and creative automation.',
    category: 'marketing',
    tags: ['video', 'generation', 'editing'],
    developerId: 'dev_runway',
    developerName: 'Runway',
    pricingModel: 'subscription',
    priceMonthly: 35,
    certified: false,
    enterpriseReady: true,
    openSource: false,
    featured: true,
    trending: true,
    installCount: 19000,
    rating: 4.5,
    reviewCount: 890,
    trustScore: 78,
    trustBadges: [],
    creditsRequired: 4,
    estimatedCostPerRun: 0.2,
    supportedPlatforms: ['web', 'api'],
    modelsUsed: ['gen-3'],
    screenshots: [],
    features: ['Video generation', 'Editing', 'Motion brush'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/runway',
    source: 'external',
    profile: profile({
      taxonomy: ['video', 'design', 'marketing'],
      subcategories: ['Video Generation', 'Editing', 'Animation'],
      capabilities: ['video', 'vision', 'multimodal'],
      supportedModels: ['other'],
      deployment: ['cloud', 'api'],
      pricing: ['subscription', 'enterprise'],
      integrations: ['slack', 'zapier'],
      compliance: ['gdpr'],
      latencyMs: 20000,
      installMethods: ['api_key', 'oauth'],
      general: {
        website: 'https://runwayml.com',
        developer: 'Runway AI',
        country: 'US',
        launchDate: '2018-01-01',
      },
    }),
  },
  {
    id: 'ext_whisper',
    slug: 'openai-whisper',
    name: 'OpenAI Whisper',
    description: 'Robust speech-to-text model family for transcription and multilingual ASR.',
    category: 'voice_ai',
    tags: ['stt', 'audio', 'open-source', 'transcription'],
    developerId: 'dev_openai',
    developerName: 'OpenAI',
    pricingModel: 'free',
    certified: true,
    enterpriseReady: true,
    openSource: true,
    featured: false,
    trending: false,
    installCount: 88000,
    rating: 4.7,
    reviewCount: 2600,
    trustScore: 90,
    trustBadges: ['Open Source', 'Gold Certified'],
    creditsRequired: 0,
    supportedPlatforms: ['local', 'api', 'docker'],
    modelsUsed: ['whisper-large-v3'],
    screenshots: [],
    features: ['Speech-to-text', 'Multilingual', 'Local deploy'],
    membershipTierRequired: 'free',
    storeRoute: '/workspace/store/apps/openai-whisper',
    workspaceRoute: '/workspace/workflows?addTool=openai-whisper',
    source: 'external',
    profile: profile({
      taxonomy: ['audio', 'research', 'customer_support'],
      subcategories: ['Speech-to-Text'],
      capabilities: ['audio'],
      supportedModels: ['gpt', 'other'],
      deployment: ['local', 'docker', 'api', 'on_premise'],
      pricing: ['free', 'pay_as_you_go'],
      integrations: ['webhook'],
      compliance: ['gdpr'],
      openSource: true,
      localDeployable: true,
      languages: ['en', 'de', 'fr', 'es', 'zh', 'ar'],
      latencyMs: 500,
      installMethods: ['docker', 'github', 'sdk', 'api_key'],
      general: {
        website: 'https://openai.com/research/whisper',
        developer: 'OpenAI',
        country: 'US',
        launchDate: '2022-09-21',
      },
    }),
  },
];

export function getExternalTool(idOrSlug: string): Tool | undefined {
  return EXTERNAL_CATALOG.find((t) => t.id === idOrSlug || t.slug === idOrSlug);
}
